//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartActS.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileAttacth
    {
        public int FileAttachId { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public Nullable<double> FileSize { get; set; }
    }
}
