//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartActS.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.Responses = new HashSet<Response>();
        }
    
        public int RequestId { get; set; }
        public string RequestCode { get; set; }
        public int CategoryId { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> DurationExpired { get; set; }
        public Nullable<decimal> FromBudget { get; set; }
        public Nullable<decimal> ToBudget { get; set; }
        public Nullable<int> RequireResponse { get; set; }
        public string ShippingAddress { get; set; }
        public Nullable<int> LocationSupplyId { get; set; }
        public string Description { get; set; }
        public Nullable<bool> BestTime { get; set; }
        public Nullable<bool> BestSupply { get; set; }
        public Nullable<bool> BestPrice { get; set; }
        public string RequestTitle { get; set; }
        public Nullable<int> FileAttrachId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Response> Responses { get; set; }
        public virtual Location Location { get; set; }
        public virtual Category Category { get; set; }
    }
}
