//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartActS.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        public int SupplyId { get; set; }
        public string SupplyCode { get; set; }
        public string SupplyName { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<double> LngTitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string MobiPhone { get; set; }
        public string Phone { get; set; }
        public string Website { get; set; }
        public Nullable<int> RankId { get; set; }
        public Nullable<int> IsStatus { get; set; }
        public string UserId { get; set; }
    }
}
